//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBI202_Creator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBI202_Creator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed.
        ///{0}.
        /// </summary>
        internal static string CreatorForm_ImportPaperSetToolStripMenuItem_Click_Import_Failed {
            get {
                return ResourceManager.GetString("CreatorForm_ImportPaperSetToolStripMenuItem_Click_Import_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open question set failed.
        ///{0}.
        /// </summary>
        internal static string CreatorForm_Open_Error {
            get {
                return ResourceManager.GetString("CreatorForm_Open_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open question set successfully..
        /// </summary>
        internal static string CreatorForm_Open_Info_Open_Successful {
            get {
                return ResourceManager.GetString("CreatorForm_Open_Info_Open_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data successfully to {0}.
        /// </summary>
        internal static string CreatorForm_Save_Info_Export_Successful {
            get {
                return ResourceManager.GetString("CreatorForm_Save_Info_Export_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose Save Location first!!!.
        /// </summary>
        internal static string ExportConfirm_exportBtn_Click_Error_Location_First {
            get {
                return ResourceManager.GetString("ExportConfirm_exportBtn_Click_Error_Location_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROC sp_CompareDb
        ///(
        ///	@SourceDB SYSNAME,
        ///	@TargetDb SYSNAME
        ///)
        ///AS
        ///BEGIN
        ////*
        ///	DECLARE @SourceDB SYSNAME=&apos;DB1&apos;,@TargetDb SYSNAME=&apos;DB2&apos;
        ///*/
        ///	SET NOCOUNT ON;
        ///	SET ANSI_WARNINGS ON;
        ///	SET ANSI_NULLS ON;   
        ///
        ///	DECLARE @sqlStr VARCHAR(8000)
        ///	SET @SourceDB = RTRIM(LTRIM(@SourceDB))
        ///	IF DB_ID(@SourceDB) IS NULL 
        ///	BEGIN
        ///		PRINT &apos;Error: Unable to find the database &apos;+ @SourceDB +&apos;!!!&apos;
        ///		RETURN
        ///	END
        ///
        ///	SET @TargetDb = RTRIM(LTRIM(@TargetDb))
        ///	IF DB_ID(@SourceDB) IS NULL 
        ///	BEGIN
        ///		PRINT &apos;Error: Unable t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImportMaterialStartCompareDb {
            get {
                return ResourceManager.GetString("ImportMaterialStartCompareDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap left {
            get {
                object obj = ResourceManager.GetObject("left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minus {
            get {
                object obj = ResourceManager.GetObject("minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minus1 {
            get {
                object obj = ResourceManager.GetObject("minus1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right {
            get {
                object obj = ResourceManager.GetObject("right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to input Test Query!.
        /// </summary>
        internal static string TestCaseDialog_insertBtn_Click_Error_Fill_Test_Query {
            get {
                return ResourceManager.GetString("TestCaseDialog_insertBtn_Click_Error_Fill_Test_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to Sql Server.
        /// </summary>
        internal static string VerifyForm_CheckConnectionButton_Click_Error_Connect_Sql {
            get {
                return ResourceManager.GetString("VerifyForm_CheckConnectionButton_Click_Error_Connect_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at DBScript for Student: {0}.
        /// </summary>
        internal static string VerifyForm_StartBtn_Click_Error_DBScript_Student {
            get {
                return ResourceManager.GetString("VerifyForm_StartBtn_Click_Error_DBScript_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at DBScript for Teacher: {0}.
        /// </summary>
        internal static string VerifyForm_StartBtn_Click_Error_DBScript_Teacher {
            get {
                return ResourceManager.GetString("VerifyForm_StartBtn_Click_Error_DBScript_Teacher", resourceCulture);
            }
        }
    }
}
